# config/routes/password_reset.yaml
password_reset_request:
    path: /password-reset
    controller: App\Controller\PasswordResetController::request

password_reset_confirm:
    path: /password-reset/confirm/{token}
    controller: App\Controller\PasswordResetController::confirm